spring.application.name=control-asistencia-backend

# Configuración de la Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/control_asistencia?serverTimezone=UTC
spring.datasource.username=root

# ⚠️ CLAVE: Escribe aquí la contraseña de tu MySQL entre el '=' y el final de la línea.
# Si no te acuerdas, las más comunes que uno suele poner son: root, admin, 1234, 123456 o root1234
spring.datasource.password=Julio071992..

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Nota: Eliminamos la línea del Dialect porque Spring Boot 3 lo detecta automáticamente.
# Nota: Eliminamos las propiedades de security.user porque ya usas tu propio 'securityConfig.java'.

# Credenciales fijas para entrar al sistema en modo prueba
